export default [
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "曹操",
    quality: "史诗",
    skillPool: "冰雷火冰",
    attack: 39,
    defense: 16,
    health: 51,
    speed: 28,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "周瑜",
    quality: "神话",
    skillPool: "雷电",
    attack: 72,
    defense: 61,
    health: 96,
    speed: 80,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "诸葛亮",
    quality: "稀有",
    skillPool: "冰火",
    attack: 4,
    defense: 55,
    health: 90,
    speed: 27,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "刘备",
    quality: "史诗",
    skillPool: "冰冻",
    attack: 49,
    defense: 29,
    health: 46,
    speed: 10,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "孙权",
    quality: "传说",
    skillPool: "冰雷火冰火",
    attack: 19,
    defense: 9,
    health: 86,
    speed: 25,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "黄盖",
    quality: "史诗",
    skillPool: "火焰",
    attack: 26,
    defense: 47,
    health: 24,
    speed: 12,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "张飞",
    quality: "传说",
    skillPool: "冰冻",
    attack: 51,
    defense: 17,
    health: 68,
    speed: 48,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "关羽",
    quality: "神话",
    skillPool: "冰火",
    attack: 26,
    defense: 83,
    health: 100,
    speed: 17,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "赵云",
    quality: "神话",
    skillPool: "冰冻",
    attack: 95,
    defense: 3,
    health: 22,
    speed: 89,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "庞统",
    quality: "普通",
    skillPool: "冰雷火冰",
    attack: 57,
    defense: 28,
    health: 23,
    speed: 46,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "鲁肃",
    quality: "稀有",
    skillPool: "冰雷",
    attack: 6,
    defense: 17,
    health: 22,
    speed: 17,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "甘宁",
    quality: "神话",
    skillPool: "冰火",
    attack: 65,
    defense: 2,
    health: 17,
    speed: 6,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "程普",
    quality: "稀有",
    skillPool: "冰火",
    attack: 8,
    defense: 56,
    health: 6,
    speed: 16,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "韩当",
    quality: "稀有",
    skillPool: "火焰",
    attack: 33,
    defense: 95,
    health: 73,
    speed: 95,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "蒋干",
    quality: "史诗",
    skillPool: "冰雷火",
    attack: 68,
    defense: 78,
    health: 14,
    speed: 49,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "蔡瑁",
    quality: "稀有",
    skillPool: "冰雷火冰",
    attack: 8,
    defense: 5,
    health: 20,
    speed: 85,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "张允",
    quality: "普通",
    skillPool: "冰冻",
    attack: 91,
    defense: 57,
    health: 31,
    speed: 40,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "许褚",
    quality: "普通",
    skillPool: "雷电",
    attack: 64,
    defense: 77,
    health: 56,
    speed: 60,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "徐晃",
    quality: "史诗",
    skillPool: "冰雷",
    attack: 98,
    defense: 29,
    health: 74,
    speed: 58,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "张辽",
    quality: "史诗",
    skillPool: "冰雷火冰火",
    attack: 63,
    defense: 15,
    health: 75,
    speed: 33,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "吕蒙",
    quality: "神话",
    skillPool: "火焰",
    attack: 3,
    defense: 57,
    health: 29,
    speed: 81,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "陆逊",
    quality: "神话",
    skillPool: "冰雷火",
    attack: 85,
    defense: 98,
    health: 23,
    speed: 30,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "太史慈",
    quality: "稀有",
    skillPool: "冰雷",
    attack: 84,
    defense: 33,
    health: 39,
    speed: 70,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "凌统",
    quality: "史诗",
    skillPool: "冰火",
    attack: 86,
    defense: 12,
    health: 96,
    speed: 72,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "诸葛瑾",
    quality: "传说",
    skillPool: "冰雷火冰",
    attack: 4,
    defense: 59,
    health: 98,
    speed: 60,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "阚泽",
    quality: "普通",
    skillPool: "冰火",
    attack: 93,
    defense: 49,
    health: 6,
    speed: 18,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "周泰",
    quality: "神话",
    skillPool: "冰火",
    attack: 94,
    defense: 37,
    health: 71,
    speed: 15,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "董袭",
    quality: "神话",
    skillPool: "冰雷火冰",
    attack: 41,
    defense: 52,
    health: 35,
    speed: 3,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "陈武",
    quality: "传说",
    skillPool: "冰雷",
    attack: 59,
    defense: 43,
    health: 97,
    speed: 11,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "丁奉",
    quality: "传说",
    skillPool: "雷电",
    attack: 48,
    defense: 99,
    health: 42,
    speed: 20,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "曹仁",
    quality: "史诗",
    skillPool: "冰雷",
    attack: 99,
    defense: 68,
    health: 56,
    speed: 47,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "夏侯惇",
    quality: "普通",
    skillPool: "冰雷火冰火",
    attack: 78,
    defense: 1,
    health: 81,
    speed: 49,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "夏侯渊",
    quality: "传说",
    skillPool: "冰火",
    attack: 36,
    defense: 16,
    health: 32,
    speed: 29,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "曹洪",
    quality: "普通",
    skillPool: "冰冻",
    attack: 36,
    defense: 79,
    health: 99,
    speed: 90,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "于禁",
    quality: "稀有",
    skillPool: "冰雷火冰",
    attack: 13,
    defense: 55,
    health: 72,
    speed: 13,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "李典",
    quality: "稀有",
    skillPool: "雷电",
    attack: 81,
    defense: 77,
    health: 64,
    speed: 63,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "乐进",
    quality: "传说",
    skillPool: "雷电",
    attack: 8,
    defense: 17,
    health: 20,
    speed: 7,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "荀彧",
    quality: "神话",
    skillPool: "冰雷火冰",
    attack: 65,
    defense: 82,
    health: 29,
    speed: 1,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "贾诩",
    quality: "稀有",
    skillPool: "冰雷",
    attack: 27,
    defense: 73,
    health: 98,
    speed: 22,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "程昱",
    quality: "传说",
    skillPool: "雷电",
    attack: 81,
    defense: 86,
    health: 55,
    speed: 24,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "毛玠",
    quality: "稀有",
    skillPool: "冰雷火",
    attack: 63,
    defense: 96,
    health: 40,
    speed: 54,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "文聘",
    quality: "普通",
    skillPool: "冰冻",
    attack: 100,
    defense: 19,
    health: 86,
    speed: 61,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "吕虔",
    quality: "稀有",
    skillPool: "雷电",
    attack: 26,
    defense: 26,
    health: 82,
    speed: 2,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "满宠",
    quality: "稀有",
    skillPool: "冰冻",
    attack: 55,
    defense: 1,
    health: 65,
    speed: 74,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "刘馥",
    quality: "神话",
    skillPool: "冰冻",
    attack: 5,
    defense: 5,
    health: 23,
    speed: 84,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "张郃",
    quality: "稀有",
    skillPool: "冰冻",
    attack: 46,
    defense: 22,
    health: 78,
    speed: 95,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "高览",
    quality: "传说",
    skillPool: "雷电",
    attack: 29,
    defense: 27,
    health: 97,
    speed: 38,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "蔡和",
    quality: "传说",
    skillPool: "冰雷火冰火",
    attack: 13,
    defense: 86,
    health: 1,
    speed: 96,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "蔡中",
    quality: "稀有",
    skillPool: "冰雷火",
    attack: 45,
    defense: 41,
    health: 98,
    speed: 22,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "马延",
    quality: "传说",
    skillPool: "冰雷火",
    attack: 4,
    defense: 39,
    health: 33,
    speed: 83,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "张顗",
    quality: "神话",
    skillPool: "冰雷火",
    attack: 37,
    defense: 48,
    health: 8,
    speed: 67,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "焦触",
    quality: "神话",
    skillPool: "雷电",
    attack: 85,
    defense: 19,
    health: 39,
    speed: 53,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "张南",
    quality: "稀有",
    skillPool: "火焰",
    attack: 33,
    defense: 60,
    health: 85,
    speed: 50,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "魏国士兵",
    quality: "史诗",
    skillPool: "冰雷",
    attack: 6,
    defense: 76,
    health: 55,
    speed: 54,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "魏国斥候",
    quality: "稀有",
    skillPool: "火焰",
    attack: 30,
    defense: 37,
    health: 93,
    speed: 79,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "魏国弓箭手",
    quality: "普通",
    skillPool: "冰雷火冰火",
    attack: 67,
    defense: 61,
    health: 27,
    speed: 4,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "魏国骑兵",
    quality: "传说",
    skillPool: "冰雷火冰火",
    attack: 77,
    defense: 46,
    health: 42,
    speed: 31,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "魏国谋士",
    quality: "传说",
    skillPool: "冰雷火冰",
    attack: 61,
    defense: 5,
    health: 85,
    speed: 11,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "魏国水军",
    quality: "稀有",
    skillPool: "雷电",
    attack: 30,
    defense: 58,
    health: 65,
    speed: 3,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "魏国副将",
    quality: "神话",
    skillPool: "冰雷火冰火",
    attack: 41,
    defense: 98,
    health: 2,
    speed: 74,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "魏国监军",
    quality: "神话",
    skillPool: "冰雷",
    attack: 39,
    defense: 53,
    health: 20,
    speed: 33,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "魏国信使",
    quality: "传说",
    skillPool: "冰火",
    attack: 9,
    defense: 4,
    health: 37,
    speed: 8,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "魏国刺客",
    quality: "神话",
    skillPool: "冰火",
    attack: 74,
    defense: 69,
    health: 100,
    speed: 12,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "魏国铁卫",
    quality: "稀有",
    skillPool: "雷电",
    attack: 61,
    defense: 33,
    health: 79,
    speed: 79,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "魏国弩手",
    quality: "史诗",
    skillPool: "冰雷火",
    attack: 3,
    defense: 64,
    health: 39,
    speed: 93,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "魏国火头军",
    quality: "传说",
    skillPool: "冰冻",
    attack: 57,
    defense: 73,
    health: 16,
    speed: 1,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "魏国医官",
    quality: "神话",
    skillPool: "冰雷",
    attack: 57,
    defense: 57,
    health: 95,
    speed: 90,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "魏国工匠",
    quality: "传说",
    skillPool: "冰雷火冰",
    attack: 50,
    defense: 92,
    health: 73,
    speed: 67,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "东吴哨兵",
    quality: "普通",
    skillPool: "冰雷火",
    attack: 24,
    defense: 60,
    health: 99,
    speed: 43,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "东吴水兵",
    quality: "稀有",
    skillPool: "冰雷",
    attack: 65,
    defense: 74,
    health: 16,
    speed: 28,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "东吴弓箭手",
    quality: "传说",
    skillPool: "冰火",
    attack: 9,
    defense: 53,
    health: 59,
    speed: 51,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "东吴骑兵",
    quality: "史诗",
    skillPool: "冰雷火冰",
    attack: 29,
    defense: 46,
    health: 82,
    speed: 86,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "东吴斥候",
    quality: "神话",
    skillPool: "冰火",
    attack: 78,
    defense: 82,
    health: 9,
    speed: 16,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "东吴医官",
    quality: "神话",
    skillPool: "冰雷",
    attack: 36,
    defense: 55,
    health: 13,
    speed: 12,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "东吴铁匠",
    quality: "传说",
    skillPool: "冰雷火冰",
    attack: 29,
    defense: 52,
    health: 28,
    speed: 29,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "东吴信使",
    quality: "传说",
    skillPool: "冰雷",
    attack: 53,
    defense: 56,
    health: 29,
    speed: 47,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "东吴百姓",
    quality: "普通",
    skillPool: "火焰",
    attack: 96,
    defense: 21,
    health: 93,
    speed: 33,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "荆州难民",
    quality: "稀有",
    skillPool: "冰火",
    attack: 10,
    defense: 92,
    health: 60,
    speed: 43,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "江夏商贩",
    quality: "稀有",
    skillPool: "冰雷火",
    attack: 97,
    defense: 43,
    health: 22,
    speed: 30,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "长江渔夫",
    quality: "稀有",
    skillPool: "雷电",
    attack: 68,
    defense: 15,
    health: 46,
    speed: 47,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "赤壁樵夫",
    quality: "普通",
    skillPool: "冰雷火冰",
    attack: 82,
    defense: 81,
    health: 31,
    speed: 19,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "乌林猎户",
    quality: "普通",
    skillPool: "冰雷火冰",
    attack: 45,
    defense: 10,
    health: 5,
    speed: 68,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "夏口医师",
    quality: "神话",
    skillPool: "冰雷火冰火",
    attack: 14,
    defense: 19,
    health: 99,
    speed: 30,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "南郡书吏",
    quality: "传说",
    skillPool: "冰雷火冰火",
    attack: 50,
    defense: 23,
    health: 14,
    speed: 38,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "樊口驿卒",
    quality: "稀有",
    skillPool: "冰雷火冰火",
    attack: 48,
    defense: 96,
    health: 54,
    speed: 33,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "三江口船夫",
    quality: "普通",
    skillPool: "冰雷火",
    attack: 23,
    defense: 63,
    health: 43,
    speed: 82,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "华容道守军",
    quality: "传说",
    skillPool: "雷电",
    attack: 84,
    defense: 37,
    health: 37,
    speed: 16,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "当阳桥民兵",
    quality: "普通",
    skillPool: "冰雷",
    attack: 94,
    defense: 83,
    health: 88,
    speed: 1,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "新野流民",
    quality: "传说",
    skillPool: "火焰",
    attack: 8,
    defense: 54,
    health: 30,
    speed: 2,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "江陵衙役",
    quality: "稀有",
    skillPool: "冰雷火冰火",
    attack: 81,
    defense: 37,
    health: 7,
    speed: 80,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "襄阳铁匠",
    quality: "传说",
    skillPool: "冰雷火",
    attack: 53,
    defense: 57,
    health: 22,
    speed: 59,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "零陵僧侣",
    quality: "传说",
    skillPool: "冰雷火冰火",
    attack: 93,
    defense: 31,
    health: 47,
    speed: 54,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "桂阳马夫",
    quality: "史诗",
    skillPool: "冰雷",
    attack: 67,
    defense: 14,
    health: 81,
    speed: 1,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "武陵药农",
    quality: "稀有",
    skillPool: "雷电",
    attack: 49,
    defense: 23,
    health: 34,
    speed: 5,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "长沙乞丐",
    quality: "史诗",
    skillPool: "冰雷火冰火",
    attack: 8,
    defense: 87,
    health: 25,
    speed: 8,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "交州行商",
    quality: "稀有",
    skillPool: "冰冻",
    attack: 49,
    defense: 39,
    health: 50,
    speed: 54,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "益州探子",
    quality: "史诗",
    skillPool: "雷电",
    attack: 24,
    defense: 77,
    health: 51,
    speed: 57,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "汉中术士",
    quality: "神话",
    skillPool: "冰雷火冰火",
    attack: 57,
    defense: 86,
    health: 47,
    speed: 85,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "西凉镖师",
    quality: "稀有",
    skillPool: "火焰",
    attack: 5,
    defense: 71,
    health: 87,
    speed: 46,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
  {
    story: "三国演义",
    plot: "赤壁之战",
    taskName: "刺杀曹操",
    character: "幽州游侠",
    quality: "传说",
    skillPool: "冰雷火冰火",
    attack: 52,
    defense: 81,
    health: 40,
    speed: 37,
    imageResource: "火烧赤壁",
    killExp: 100,
    dropItems: "小袋金钱,异常点",
  },
];
