import React, { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import {
  Container,
  TextField,
  Button,
  Grid,
  Typography,
  Box,
  FormControlLabel,
  Checkbox,
  InputAdornment,
  IconButton,
} from "@mui/material";
import axios from "axios";
import localforage from "localforage";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { Visibility, VisibilityOff } from "@mui/icons-material";
import { useRouter } from "next/navigation";
import UserLogin from "@/components/pages/user/login";

const theme = createTheme({
  palette: {
    primary: { main: "#1976d2" },
    error: { main: "#d32f2f" },
  },
});

const LoginForm = () => {
  const [formData, setFormData] = useState({
    username: "",
    email: "",
    password: "",
    showPassword: false,
    remember: false,
  });

  const [errors, setErrors] = useState({
    username: false,
    // email: false,
    password: false,
  });
  const router = useRouter();
  const validateEmail = (email) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = {
      //   email: !validateEmail(formData.email),
      username: formData.username.trim() === "",
      password: formData.password.trim() === "",
    };

    setErrors(newErrors);

    if (!Object.values(newErrors).some((error) => error)) {
      // 登录逻辑
      console.log("Login  submitted:", formData);
      // 这里可以添加axios.post('/api/login',  formData)等API调用
      axios({
        url: "/api/user/login",
        method: "post",
        data: formData,
      }).then((res) => {
        if (formData.remember) {
          localforage.setItem("access_token", res.data.access_token);
        }
        axios({
          url: "/api/user/cards",
          method: "get",
        }).then((res) => {
          console.log(res);

          const myCardsReq = [];
          for (let index = 0; index < res.data.length; index++) {
            const element = res.data[index];
            myCardsReq.push(
              axios({
                url: "/api/card/info",
                method: "get",
                params: {
                  cardId: element.card_id,
                },
              })
            );
          }
          Promise.all(myCardsReq).then((res) => {
            console.log(res);
            const myCards = [];
            for (let index = 0; index < res.length; index++) {
              const element = res[index];
              myCards.push(element.data);
            }
            localforage.setItem("my-cards", myCards);
          });
        });

        // router.push("/journey/content");
      });
    }
  };

  const handleChange = (prop) => (event) => {
    setFormData({
      ...formData,
      [prop]: prop === "remember" ? event.target.checked : event.target.value,
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <UserLogin />
      </main>
    </>
  );
};

export default LoginForm;
