import React, { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import {
  Container,
  TextField,
  Button,
  Grid,
  Typography,
  Box,
  FormControlLabel,
  Checkbox,
  InputAdornment,
  IconButton,
} from "@mui/material";
import axios from "axios";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { Visibility, VisibilityOff } from "@mui/icons-material";
import UserRegister from "@/components/pages/user/register";
import { useRouter } from "next/navigation";

const theme = createTheme({
  palette: {
    primary: {
      main: "#1976d2",
    },
    error: {
      main: "#d32f2f",
    },
  },
});

const RegisterForm = () => {
  const [formData, setFormData] = useState({
    username: "",
    email: "",
    password: "",
    confirmPassword: "",
    showPassword: false,
  });

  const [errors, setErrors] = useState({
    username: false,
    email: false,
    password: false,
    confirmPassword: false,
  });
  const router = useRouter();
  const validateEmail = (email) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);

  const validatePassword = (password) =>
    password.length >= 8 && /[A-Z]/.test(password) && /\d/.test(password);

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = {
      username: formData.username.trim() === "",
      email: !validateEmail(formData.email),
      password: !validatePassword(formData.password),
      confirmPassword: formData.password !== formData.confirmPassword,
    };

    setErrors(newErrors);

    if (!Object.values(newErrors).some((error) => error)) {
      // 提交表单逻辑
      axios({
        url: "/api/user/regist",
        method: "post",
        data: formData,
      }).then((res) => {
        if (res.data) {
          router.push("/user/login");
        }
      });
      console.log("Form  submitted:", formData);
    }
  };

  const handleChange = (prop) => (event) => {
    setFormData({ ...formData, [prop]: event.target.value });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <UserRegister />
      </main>
    </>
  );
};

export default RegisterForm;
